FRECUENCY_MONTHLY = 1
FRECUENCY_FORTNIGHTLY = 2
FRECUENCY_WEEKLY = 3
FRECUENCY_DAILY = 4

FRECUENCY_MONTHLY_STR = "Mensual"
FRECUENCY_FORTNIGHTLY_STR = "Quincenal"
FRECUENCY_WEEKLY_STR = "Semanal"
FRECUENCY_DAILY_STR = "Diario"